#!/usr/bin/env bash

# Exit immediately if an error occurs
set -e

# Function to display usage information
usage() {
    echo "ℹ️  Usage: $(basename "$0") [OPTIONS]"
    echo ""
    echo "Description:"
    echo "  This script restores R packages for a specified project directory containing an 'renv.lock' file."
    echo "Options:"
    echo "  -d, --directory DIRECTORY        Project directory containing 'renv.lock' file. Default is current directory."
    echo "  -r, --restore                    Run renv::restore(transactional = TRUE) within the project. Default is true."
    echo "  -e, --exclude PKG1,PKG2          Comma-separated list of packages to exclude from restore."
    echo "  -p, --pak                        Use pak for package management."
    echo "  -D, --debug                      Enable debug mode."
    echo "  -h, --help                       Display this help message."
    exit 1
}

PROJECT_DIR="."
RESTORE=false
PKG_EXCLUDE=""
DEBUG=false
USE_PAK=false

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -r|--restore)
            RESTORE=true
            shift
            ;;
        -e|--exclude)
            if [[ -n "${2:-}" && ! "$2" =~ ^- ]]; then
                PKG_EXCLUDE="$2"
                shift 2
            else
                echo "❌ --exclude requires a non-empty package name argument."
                usage
            fi
            ;;
        -p|--pak)
            USE_PAK=true
            shift
            ;;
        -D|--debug)
            DEBUG=true
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "❌ Unknown parameter passed: $1"
            usage
            ;;
    esac
done

debug() {
    if [ "$DEBUG" = true ]; then
        echo "🐛 DEBUG: $1"
    fi
}

debug "Running renv-restore"
debug "PROJECT_DIR: $PROJECT_DIR"
debug "RESTORE: $RESTORE"
debug "PKG_EXCLUDE: $PKG_EXCLUDE"
debug "USE_PAK: $USE_PAK"

# Activate project
renv_activate() {
    echo "🔍 Activating project"
    Rscript -e "
        tryCatch(
            renv::activate(),
            error = function(e) {
                message('⚠️  Activation threw error: ', e)
            }
        )"
    echo "✅ Activation process attempted"
    echo "---------------------------------------------"
}

restore_renv() {
    echo "Restoring original renv version"
    Rscript -e "
        tryCatch(
            renv::restore(packages = 'renv', transactional = TRUE),
            error = function(e) {
                message('⚠️  Restore failed: ', e)
            }
        )"
}

install_pkg() {
    echo "🔍 Installing $1"
    Rscript -e "
    tryCatch( 
        {  
            Sys.setenv(RENV_CONFIG_PAK_ENABLED = 'false')
            if (isFALSE(requireNamespace('$1', quietly = TRUE))) {
                message('🔍 $1 not found. Installing $1...')
                utils::install.packages('$1', repos = 'https://cloud.r-project.org')
            } else {
                message('✅ $1 is already installed.')
            }
        },
        error = function(e) {
            message('⚠️  Installation failed: ', e)
        }
    )"
    echo "✅ Installation process attempted"
    echo "---------------------------------------------"
}

install_pak_bioc() {
    echo "🔍 Installing pak and BiocManager"
    install_pkg pak
    install_pkg BiocManager
}

if [ "$USE_PAK" = true ]; then
    export RENV_CONFIG_PAK_ENABLED=true
fi

restore() {
    echo "🔄 Attempting to restore packages"
    if [ -n "$PKG_EXCLUDE" ]; then
        EXCLUDE_ARRAY=$(echo "$PKG_EXCLUDE" | sed "s/,/\",\"/g")
        debug "EXCLUDE_ARRAY: $EXCLUDE_ARRAY"
        Rscript -e "
            tryCatch(
                {
                    if ('transactional' %in% names(formals(renv::restore))) {
                        renv::restore(exclude = c(\"$EXCLUDE_ARRAY\"), transactional = TRUE)
                    } else {
                        renv::restore(exclude = c(\"$EXCLUDE_ARRAY\"))
                    }
                },
                error = function(e) {
                    message('⚠️  Restore failed: ', e)
                }
            )"
    else
        Rscript -e "
            tryCatch(
                {
                    if ('transactional' %in% names(formals(renv::restore))) {
                        renv::restore(transactional = TRUE)
                    } else {
                        renv::restore()
                    }
                },
                error = function(e) {
                    message('⚠️  Restore failed: ', e)
                }
            )"
    fi
    echo "✅ Restore process attempted"
    echo "---------------------------------------------"
}

run_custom_scripts() {
    if [ -f "config-r-renv.sh" ]; then 
        echo "🔍 Found shell script"
        if ! ./config-r-renv.sh "$PKG_EXCLUDE"; then
            echo "⚠️  Project-specific shell script failed"
            echo "---------------------------------------------"
        fi
    fi

    if [ -f "config-r-renv.R" ]; then
        echo "🔍 Found R script"
        cd "$PROJECT_DIR"
        if ! Rscript config-r-renv.R "$PKG_EXCLUDE"; then
            echo "⚠️  Project-specific R script failed"
            echo "---------------------------------------------"
        fi
    fi
}

main() {
    ORIG_DIR=$(pwd)
    PROJECT_NAME=$(basename "$PROJECT_DIR")
    echo "🚀 Processing project: $PROJECT_NAME"
    trap 'cd "$ORIG_DIR"' EXIT
    cd "$PROJECT_DIR"
    renv_activate
    install_pak_bioc
    restore
    run_custom_scripts
    echo "✅ Finished processing project: $PROJECT_NAME"
    echo "---------------------------------------------"
}

main
