name: Check Quarto Website

on:
  pull_request:
    paths:
      - "docs/**"
      - "scripts/docs_catalogue.py"
      - ".github/workflows/check-docs.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2.2.0

      - name: Render Quarto site
        run: quarto render docs
